name: ddasigae_flutter
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  geolocator: ^10.1.0
  flutter_native_splash: ^2.3.5
  logging: ^1.2.0
  shared_preferences: ^2.2.2
  http: ^0.13.3
  flutter_dotenv: ^5.1.0
  carousel_slider: ^4.2.1
  flutterfire_cli: ^0.2.7
  firebase_core: ^2.24.2
  go_router: ^9.0.3
  flutter_riverpod: ^2.3.6

  google_sign_in: ^6.1.4

  image_picker: ^0.8.9
  dots_indicator: ^3.0.0

  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

  flutter_image_compress: ^2.0.3

  cloud_firestore: ^4.8.1
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.4.5
  freezed: ^2.3.5
  json_serializable: ^6.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - .env

  fonts:
    - family: koPubWorldDotum
      fonts:
        - asset: assets/fonts/KoPubWorld Dotum Light.ttf
          weight: 300
        - asset: assets/fonts/KoPubWorld Dotum Medium.ttf
          weight: 500
        - asset: assets/fonts/KoPubWorld Dotum Bold.ttf
          weight: 700
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit-Regular.ttf
          weight: 300
